// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var $faq;
    $faq = $('#faq');
    $faq.append('<dl id="faqList" class="accordion" data-accordion></dl>');
    $.getJSON('js/faq.json', function(data) {
      var $faqList;
      $faqList = $('#faqList');
      return $(data.questions).each(function(i, value) {
        return $faqList.append('<dd class=""><a href="#panel' + (i + 1) + '"><h3>' + value.q + '</h3></a><div id="panel' + (i + 1) + '" class="content">' + value.a + '</div></dd>');
      });
    });
    return $(document).foundation();
  });

}).call(this);
